### ISSUE TITLE
`verifylto` needs database

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ltopers#106]
- move `verifylto` from general function to database-related functions
- a database-independent verification should also be implemented

**Comment by privatezero** [comment]
All the DB related functions in `verifylto` are contained in `if [ "${PREMIS_DB}" = "Y" ] ; then` conditionals and shouldn't have any effect on the normal usage of `verifylto` unless the DB is specifically configured and turned on using `mmconfig.`

I wouldn't classify it as dependent on the DB, as it can function totally independently of the DB as well.

**Comment by retokromer** [comment]
Thank you very much! Then I should add a test like:
```
if [[ $(which one_of_the_db_functions) ]]; then
    . . .
fi
```
just before this test, I suppose? (The goal is to allow using the basic function in a broader context.)

**Comment by retokromer** [comment]
Thank you very much! https://github.com/amiaopensource/ltopers/pull/107 should resolve this without need to move the function (nor to create another one).
