### ISSUE TITLE
/usr/local/bin/mmfunctions: line 43: usage: command not found

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#11]
/Users/medialab
≈:≈ writelto -e N -t /Volumes/LT003A/ /Volumes/3TB_LTO/ 
/Volumes//Volumes/LT003A/ is not a directory.
/usr/local/bin/mmfunctions: line 43: usage: command not found

/Users/medialab
≈:≈ 

LT003A is the mounted LTO tape.

**Comment by NMAAHC** [comment]
Never mind!

**Comment by dericed** [comment]
huh?
it should be _usage (we prefixed internal functions with underscores)

**Comment by NMAAHC** [comment]
I typed in the tape number wrong for the target. I don't know about line 43. Seems to be working fine now. 

gcp needs a verbosity speed of transmission hack :)

**Comment by dericed** [comment]
still a bug since the usage function doesn't run.
