### ISSUE TITLE
running out of space on tape

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#12]
Using writelto to write 2.14TB of data to LTO6 tape, capacity 2.41.

Continually, I am running out of space on tape. My guess it has to do with the temp files being written by rsync...? Largest file in transfer is 288G. 2.14 + .28 = 2.42. Would it make sense that a temp file is causing the space issue? 

Any way around this?

Specific log error - rsync exited with 11 on the first pass and  on the second pass.

2016/06/14 02:42:31 [4891] building file list
2016/06/14 02:42:31 [4891] 20160614-024230 'Volumes/3TB_LTO/LT004A/.' 136 '/Volumes/LT004A/'
2016/06/14 05:25:53 [4891] 20160614-024230 'Volumes/3TB_LTO/LT004A/2015_167_1_1__Boy_What_A_Girl_R2/2015_167_1_1__Boy_What_A_Girl__Derivatives_R2/2015_167_1_1__DER_02_R2.mov' 288343503197 '/Volumes/LT004A/'
2016/06/14 05:25:53 [4891] rsync: read errors mapping "/Volumes/3TB_LTO/LT004A/2015_167_1_1__Boy_What_A_Girl_R2/2015_167_1_1__Boy_What_A_Girl__Derivatives_R2/2015_167_1_1__DER_02_R2.mov": Input/output error (5)
2016/06/14 05:25:53 [4891] WARNING: 2015_167_1_1__Boy_What_A_Girl_R2/2015_167_1_1__Boy_What_A_Girl__Derivatives_R2/2015_167_1_1__DER_02_R2.mov failed verification -- update discarded (will try again).
2016/06/14 07:02:05 [4891] rsync: write failed on "/Volumes/LT004A/2015_167_1_1__Boy_What_A_Girl_R2/2015_167_1_1__Boy_What_A_Girl__Derivatives_R2/2015_167_1_1__DER_02_R2.mov": No space left on device (28)
2016/06/14 07:30:40 [4891] rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]

**Comment by dericed** [comment]
That makes sense, but have you tried the same with the latest version of writelto which uses gcp?

**Comment by NMAAHC** [comment]
We are running the latest version, I believe.

/Users/medialab
≈:≈ brew install ltopers
Warning: amiaopensource/amiaos/ltopers-0.1.2_3 already installed

**Comment by retokromer** [comment]
How many files do you have?

The default LTSF initialisation by `formatlto` allows smaller files to live in the index partition, which gives faster access, but needs more space on the cartridge.

**Comment by NMAAHC** [comment]
This can be closed. Issue was a corrupt file. Thanks!

**Comment by retokromer** [comment]
Thank you for the feedback!
