### ISSUE TITLE
function `_check_for_lto_index_dir` is not defined

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ltopers#120]
The line https://github.com/amiaopensource/ltopers/blob/master/writelto#L14 gives an error message.

This function has been added in https://github.com/amiaopensource/ltopers/pull/118/commits/69a63a2600f1fc8024eb4e4daa87a158abb03a42 but is not present in `mm`.

cc @BleakleyMcD

**Comment by retokromer** [comment]
Is addressed in https://github.com/mediamicroservices/mm/pull/178/files.

**Comment by retokromer** [comment]
This has been resolved in the HEAD, but waiting for the next release of `mm`, before closing the issue.

**Comment by retokromer** [comment]
This issue will be resolved once a [new release](https://github.com/mediamicroservices/mm/releases) of `mm` is made.

**Comment by retokromer** [comment]
@CSchloss385 Do you have the rights for release a version 2.3.1 of `mm`?

**Comment by CSchloss385** [comment]
@retokromer I do. I'll go ahead and make a new release.

**Comment by retokromer** [comment]
Thank you very much, @CSchloss385!
