### ISSUE TITLE
${RSYNC_ERR_2} is not reporting

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#14]
rsync error reports are not reporting err_2. It is just blank.

ex. 

rsync exited with 23 on the first pass and  on the second pass.
rsync exited with 0 on the first pass and  on the second pass.

**Comment by NMAAHC** [comment]
We are still experiencing this issue. Minor annoyance :)

**Comment by privatezero** [comment]
Looks like the script only actually runs a second pass of rsync as part of the process where it eliminates hidden files (so if there are no hidden files then the value that would be reported is null).   Changed the reporting to account for sometimes only one pass being run in https://github.com/amiaopensource/ltopers/pull/28/commits/d0f4d62fb0d7cfa4f99f8e3105664c33ae6d8f7a.

**Comment by NMAAHC** [comment]
Thanks!

**Comment by dericed** [comment]
Closed by https://github.com/amiaopensource/ltopers/pull/28/commits/d0f4d62fb0d7cfa4f99f8e3105664c33ae6d8f7a. Thanks @privatezero.
