### ISSUE TITLE
clarification for LTO  naming

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ltopers#164]
Users at MIPoPS were following the directions for running `formatlto` for the first time and ran into some problems with the naming conventions. When they read the following:

>The script will ask you select a deck (if you have more than one attached) and to name your tape. There are two different tape ID formats:
the 6-char ID must be exactly 6 capital letters and/or numbers
 the 8-char ID must be exactly 6 capital letters and/or numbers, followed by 'L5', 'L6' or 'L7' specifying the LTO generation.

they interpreted this as meaning they could use _either_ a 6 or 8 character tape ID and selected an 8 character id `MIPOPSL7` which lead to an error due to the ID not being 6 characters.  They have since switched to the format of `A00001 ...` with success.

I guess that the documentation here could be cleaned up a little bit to make this difference a little more clear for institutions transitioning to LTOpers for the first time? I would edit myself, but I have only worked with 6 character conventions and am not sure of when an 8 character tape id would work and when it will fail. Is this dependent on machine?

**Comment by dericed** [comment]
8 char ids were added in https://github.com/amiaopensource/ltopers/commit/0f83013ffd9edda6f0140aecf3575a1943b43397. Can you confirm what error mkltfs provides when an 8 character id is used?

**Comment by privatezero** [comment]
Here is their terminal output:
![image](https://user-images.githubusercontent.com/12941699/36231140-c9f50996-1191-11e8-8bf8-704b221b8871.png)

note the `Tape serial must be 6 characters`

**Comment by retokromer** [comment]
It depends on which system you are running. I guess, the CUNY-style needs 6 characters [A-Z][0-9], some racks work with the additional two characters, which facilitates the management of a mix of different generations. I did add the second format as well, in order to be able to use LTOpers in both contexts.

**Comment by retokromer** [comment]
(On which version are you running? The current one should work with LTO-8 as well. Possibly I forgot to update this.)

**Comment by dericed** [comment]
I can't find source code for mkltfs that permits a tape-serial not equal to 6 characters. https://github.com/amiaopensource/ltfs/blob/e9a6b8283cfae855cacfa8026bfd5aa7e8d476cc/ltfs/messages/bin_mkltfs/root.txt#L68-L69

@retokromer could you please cite a mkltfs source that permits longer strings as the tape serial number?

**Comment by retokromer** [comment]
@dericed I’m afraid, not from the top of my head: I have to check the docs… I know we have used `LTOpers` in an 8-chars system for one (I guess) customer here in Switzerland and two (I guess) in Europe. Possibly related to https://github.com/amiaopensource/ltopers/issues/69?

**Comment by privatezero** [comment]
Thank you!
