### ISSUE TITLE
unable to mount tape with mountlto

### ISSUE THREAD

**Issue by DK10101** [amiaopensource/ltopers#189]
Hello All

I'm quite new to LTO / LTFS and I'm reaching out as I feel you may be able to point me in the right direction.

**$ mountlto
 Checking for ready tapes...
Checking for tape barcode.....**
 **Checked 1 decks and none appear to have tapes ready to mount.**

Any tips on getting this tape to mount successfully?

Background:

I have recently acquired an standalone mLogic LTO-6 Thunderbolt tape drive. I've had issues with the mLogic GUI- i have transferred 3 folders of data in 3 separate sessions, however I am unable to access this data. When I mount the tape through the GUI I can clearly see that 2.4TB are 'in use' as it is noted below the options menu, however when I go to retrieve this data it is nowhere to be seen. It seems that the tape is being partitioned and I'm unable to see / access these partitions. The tape is also not visible in my 'volumes' in finder, which is strange as I'd have thought it would appear there like any other drive. It mounts through the following: 

/Users/editor/Library/Application\ Support/mTape\ LTFS\ Utility/.MountIndexData/147291539 

I initially named the tape AAL210 and it would appear as such when I see the drive in Mac 'Computer', however now it appears as a 9 digit number instead of the tape ID I assigned it.

What I'm trying to do:

I'm currently trying to access the tape through terminal using LTOPERS in an attempt to access all of the data on the tape. I keep running into an error and the tape is unable to mount, perhaps you could point me in the right direction. Here is some additional information.

Thanks in advance,
Dean

$ ltfs -f
307 LTFS14000I LTFS starting, LTFS version 2.4.0.2 (10071), log level 2.
307 LTFS14058I LTFS Format Specification version 2.4.0.
307 LTFS14104I Launched by "ltfs -f".
307 LTFS14105I This binary is built for Mac OS X .
307 LTFS14106I GCC version is 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66)).
307 LTFS17087I Kernel version: Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64.
307 LTFS14063I Sync type is "time", Sync time is 300 sec.
307 LTFS17085I Plugin: Loading "iokit" tape backend.
307 LTFS17085I Plugin: Loading "unified" iosched backend.
307 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
307 LTFS30810I Opening a device through iokit driver (0).
307 LTFS30814I Vendor ID is IBM     .
307 LTFS30815I Product ID is 'ULTRIUM-HH6     '.
307 LTFS30816I Firmware revision is JAX1.
307 LTFS30817I Drive serial is 10WT135434.
307 LTFS17160I Maximum device block size is 1048576.
307 LTFS11330I Loading cartridge.
307 LTFS30854I Logical block protection is disabled.
307 LTFS11332I Load successful.
307 LTFS17157I Changing the drive setting to write-anywhere mode.
307 LTFS11005I Mounting the volume.
307 LTFS30854I Logical block protection is disabled.
307 LTFS17227I Tape attribute: Vendor = IBM     .
307 LTFS17227I Tape attribute: Application Name = LTFS                            .
307 LTFS17227I Tape attribute: Application Version = 2.4.0.2 .
307 LTFS17227I Tape attribute: Medium Label = AAL216.
307 LTFS17228I Tape attribute: Text Localization ID = 0x81.
307 LTFS17227I Tape attribute: Barcode = AAL216                          .
307 LTFS17227I Tape attribute: Application Format Version = 2.4.0           .
307 LTFS17228I Tape attribute: Volume Lock Status = 0x00.
307 LTFS17227I Tape attribute: Media Pool name = .
307 LTFS14094E Cannot get mount point (0).
307 LTFS30854I Logical block protection is disabled.

$ system_profiler SPSASDataType
SAS:

    SAS Domain 0:

      Vendor: ATTO Technology, Inc.
      Product: ATTO ExpressSAS H608
      Revision: 0
      Initiator Identifier: 65536
      SAS Address: 50:01:08:60:00:96:00:A0

        SCSI Target Device @ 0:

          SAS Address: 50:05:07:63:12:56:BB:FD
          SCSI Target Identifier: 0
          SCSI Peripheral Device Type: 1
          Manufacturer: IBM
          Model: ULTRIUM-HH6
          Revision: JAX1

            SCSI Logical Unit @ 0:

 
              LUN Address: 00:00:00:00:00:00:00:00

**Comment by dericed** [comment]
There's a line at https://github.com/amiaopensource/ltopers/blob/09062b5b9d0dcb1156222419764d070d928507b5/mountlto#L53, where the output of `ltfs -f -o devname=0` is grepped for the barcode and with your output that value is `.` since that follows the barcode in

>307 LTFS17227I Tape attribute: Barcode = AAL216 .

The process to get the barcode value from that output should be updated to find the barcode value rather than the last value in the line as it currently does.

**Comment by DK10101** [comment]
Thanks a million!
