### ISSUE TITLE
/usr/local/bin/formatlto: line 90: mkltfs: command not found

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#205]
/Users/medialab
≈:≈ formatlto
1) 0
2) 32
Which LTO deck? 2
Enter the tape identifier: CHICAG
/usr/local/bin/formatlto: line 90: mkltfs: command not found

/Users/medialab
≈:≈

**Comment by retokromer** [comment]
Could you possibly run the commands `mkltfs --help` and `mkltfs --version` and post the results?

**Comment by NMAAHC** [comment]
/Users/medialab
≈:≈ mkltfs --help && mkltfs --version
-bash: mkltfs: command not found

hmmm

**Comment by retokromer** [comment]
That means that the command is not installed. Does `ltfs --help` respond?

**Comment by NMAAHC** [comment]
/Users/medialab
≈:≈ ltfs --help
-bash: ltfs: command not found

/Users/medialab
≈:≈ brew install ltopers
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Warning: amiaopensource/amiaos/ltopers 2019-01-22 is already installed and up-to-date
To reinstall 2019-01-22, run `brew reinstall ltopers`

/Users/medialab
≈:≈ brew reinstall ltopers
==> Reinstalling amiaopensource/amiaos/ltopers --with-cuny
==> Downloading https://github.com/amiaopensource/ltopers/archive/v2019-01-22.tar.gz
Already downloaded: /Users/medialab/Library/Caches/Homebrew/downloads/10817392b527e92855d994a793a64ccb24e59357b95ce8e05676d0be3ea610cd--ltopers-2019-01-22.tar.gz
🍺  /usr/local/Cellar/ltopers/2019-01-22: 17 files, 44.7KB, built in 3 seconds

/Users/medialab
≈:≈ formatlto
1) 0
2) 32
Which LTO deck? 2
Enter the tape identifier: CHICAG
/usr/local/bin/formatlto: line 90: mkltfs: command not found

**Comment by retokromer** [comment]
This is not related to `LTOpers`. The LTFS utilities are not installed (see the [link](https://www.quantum.com/serviceandsupport/softwareanddocumentationdownloads/ltfs/index.aspx?whattab=Third) in the README to download this).

**Comment by NMAAHC** [comment]
ahh, oops. Thank you. Sometimes, on Saturdays, we forget to read.
