### ISSUE TITLE
report to a database

### ISSUE THREAD

**Issue by dinahhandel** [amiaopensource/ltopers#4]
Sometimes there is an error with the way that lto2filemaker delivers information to filemaker, and if a show has been written to lto it doesn't always show up in the filemaker database.

**Comment by dinahhandel** [comment]
This is still true! And, more importantly, we need to ensure that lto2filemaker is reporting/reading the file path from the rsync log correctly.

**Comment by dericed** [comment]
Possibly with some @jfarbowitz style, we could switch out from filemaker to some more open form of database (sqlite/mysql).

**Comment by retokromer** [comment]
MariaDB is _the_ free replacement of MySQL: https://github.com/MariaDB

**Comment by dinahhandel** [comment]
Another issue to resolve with lto2filemaker, which is specific to CUNY TV and our data migration, is to make sure that the database reflects the tape that the material has migrated to. This can be done by reporting additional information from the schema file to the database, such as the tape number. Presently, after writing a tape, we receive the following output about updating the database: 
Uploading tape metadata for tape name=E00002. Please wait…
 Uploading file metadata for tape name=E00002. Please wait…
 The database already knows about a file in E00002.schema called name=AWW00001.mov
 The database already knows about a file in E00002.schema called name=AWW00002.mov
 The database already knows about a file in E00002.schema called name=AWW00003.mov
 The database already knows about a file in E00002.schema called name=AWW00004.mov
 The database already knows about a file in E00002.schema called name=AWW00005.mov
 The database already knows about a file in E00002.schema called name=AWW00006.mov
 The database already knows about a file in E00002.schema called name=AWW00007.mov
 The database already knows about a file in E00002.schema called name=AWW00008.mov
 The database already knows about a file in E00002.schema called name=AWW00009.mov
 The database already knows about a file in E00002.schema called name=BDC00235.mov
 The database already knows about a file in E00002.schema called name=BDC00246.mov
 The database already knows about a file in E00002.schema called name=BDC00247.mov
 The database already knows about a file in E00002.schema called name=BDC00248.mov
 The database already knows about a file in E00002.schema called name=BDC00249.mov
 The database already knows about a file in E00002.schema called name=BDC00250.mov
 The database already knows about a file in E00002.schema called name=BDC00251.mov
 The database already knows about a file in E00002.schema called name=BDC00252.mov
 The database already knows about a file in E00002.schema called name=BDC00253.mov
etc.

**Comment by dinahhandel** [comment]
@dericed don't forget about this!!! :)

**Comment by dericed** [comment]
B)

**Comment by dericed** [comment]
Updating the title of this. The lto2filemaker script uses the Filemaker Server XML api which is awkward and horribly slow, so changing this thread to consider other database options. @retokromer suggests MariaDB, @privatezero is doing something similar with MySQL.

I suggest these functions for a database:
- store entirety of the LTO schema in database tables
- allow some sort of command line `ltosearch` tool to query what file is where, when written, etc.

Other considerations?

**Comment by retokromer** [comment]
I agree with @dericed 

The SQL commands for MySQL (controlled by Oracle) and MariaDB (a fork when Oracle tock over MySQL) should be identical. We replaced some years ago, in 2013 if I remember carefully.

**Comment by retokromer** [comment]
Yes, in 2013 (e.g. https://retokromer.ch/publications/FilmXML.html).

**Comment by dericed** [comment]
partly (maybe fully) resolved by https://github.com/amiaopensource/ltopers/pull/25. Comments welcome.

**Comment by privatezero** [comment]
Yes! Comments/critiques please! Still a bunch to be worked out!

**Comment by retokromer** [comment]
Is this still an open issue, @dinahhandel?

**Comment by dericed** [comment]
https://github.com/amiaopensource/ltopers/pull/25 is partly resolving, but there's plans to report on data from the schema file to a database. I believe @privatezero has this in the works.

**Comment by retokromer** [comment]
Thank you for the update! (Then I don’t close ;-)

**Comment by dericed** [comment]
IIUC, this [part](https://github.com/amiaopensource/ltopers/issues/4#issuecomment-276168959) was resolved by https://github.com/amiaopensource/ltopers/pull/46. Thanks to @privatezero
