### ISSUE TITLE
formatlto query is malformed

### ISSUE THREAD

**Issue by dericed** [amiaopensource/ltopers#63]
After https://github.com/amiaopensource/ltopers/commit/0f83013ffd9edda6f0140aecf3575a1943b43397

on a mac when we run `formatlto`, we get:

```
1) 0
2) 0
\033[1;34mWhich LTO deck? \033[0m
```

:(

**Comment by retokromer** [comment]
@dericed Then it was a bad idea to use `mmfunctions`… I’ll revert the PS3 part very soon.
