### ISSUE TITLE
warning on writelto with deckserial-named mount

### ISSUE THREAD

**Issue by dericed** [amiaopensource/ltopers#75]
On some ltfs instances, mountlto is unable to determine the tape name and thus uses the deck serial number as a backup. When using writelto, then, the deck serial is used for the `-t` option. However recently writelto is checking the value of `-t` against the barcode regex so the command gives warnings such as this:

```
time writelto -t HU1212MNU1 /Volumes/GDRIVE8/WRITETHIS
HU1212MNU1 is not valid. The tape id must be exactly 6 capital letters and/or numbers, possibly followed by 'L5', 'L6' or 'L7' specifying the LTO generation.
writelto 0.9
This script writes the contents of a specified directory onto a mounted
LTFS-formated LTO tape.
Dependencies: mmfunctions
Usage: writelto -t [-e] [-v] | -h  -t  tape serial
  -e  state yes (Y) or no (N) to ejecting the tape after write, default
      is yes
  -v  reads back and creates checksums for the contents of a tape, and
      writes checksums to a file named with the tape name and date,
      located in the LTO logs directory
  -h  display this help
cat: /Volumes/GDRIVE8/WRITETHIS/tapechecksum.md5: No such file or directory
'/Volumes/GDRIVE8/WRITETHIS/WRITETHIS.mov' -> '/Volumes/HU1212MNU1/WRITETHIS.mov'
```

I think since mountlto can not in all cases get the tape barcode, then `-t` in writelto should be flexible.

Also I see there's a cat error since it's looking for a file that is not there.

**Comment by retokromer** [comment]
My guess:
- at line https://github.com/amiaopensource/ltopers/blob/master/writelto#L24 should be cut after `-h`
- at line https://github.com/amiaopensource/ltopers/blob/master/writelto#L50 `_usage` should be replaced by `exit 1`

**Comment by privatezero** [comment]
@dericed, is this along the lines of what you were thinking? Warn and proceed?

https://github.com/amiaopensource/ltopers/compare/address-75#diff-0d7b535ba780514a0dc02792a26a2e05R49

**Comment by dericed** [comment]
LGTM

**Comment by retokromer** [comment]
LGTM (will test IRL from Good Friday on).
