### ISSUE TITLE
warn or suggest when a permission issue blocks the creation of a directory to mount to

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#8]
I can mountlto with sudo but not without. Unsure why.

/Users/medialab
≈:≈ mountlto
Enter the 6 character tape number: LT001B
MOUNTING TAPE : THE TAPE WILL MOUNT TO THE /Volumes/LT001B FOLDER
MOUNTING TAPE : AFTER MOUNT PRESS CONTROL-C TO EJECT
mkdir: /Volumes/LT001B: Permission denied
507 LTFS14000I LTFS starting, LTFS version 2.2.0.1 (5100), log level 2
507 LTFS14058I LTFS Format Specification version 2.2.0
507 LTFS14104I Launched by "ltfs -f -o work_directory=/Users/medialab/Documents/lto_indexes -o eject -o capture_index -o devname=0 -o volname=LT001B -o uid=503 -o sync_type=unmount /Volumes/LT001B"
507 LTFS14105I This binary is built for Mac OS X 
507 LTFS14106I GCC version is 4.2.1 (Apple Inc. build 5666) (dot 3)
507 LTFS17087I Kernel version: Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64
507 LTFS14064I Sync type is "unmount"
507 LTFS17085I Plugin: Loading "iokit" driver
507 LTFS17085I Plugin: Loading "unified" iosched
507 LTFS12158I Opening a device through iokit driver (0)
507 LTFS12118I Drive identification is 'ULTRIUM-HH6     '
507 LTFS12162I Vendor ID is IBM  
507 LTFS12159I Firmware revision is E4J1
507 LTFS12160I Drive serial is 10WT045909
507 LTFS17160I Maximum device block size is 1048576
507 LTFS17157I Changing the drive setting to append-only mode
507 LTFS11005I Mounting the volume
507 LTFS12207I Logical block protection is disabled
507 LTFS17227I Tape attribute: Vendor = IBM  
507 LTFS17227I Tape attribute: Application Name = LTFS  
507 LTFS17227I Tape attribute: Application Version = 2.2.0.1 
507 LTFS17227I Tape attribute: Medium Label = LT001B
507 LTFS17228I Tape attribute: Text Localization ID = 0x81
507 LTFS17227I Tape attribute: Barcode = LT001B  
507 LTFS17227I Tape attribute: Application Format Version = 2.2.0  
fuse: bad mount point `/Volumes/LT001B': No such file or directory
507 LTFS14094E Cannot get mount point (-1)
507 LTFS12207I Logical block protection is disabled

/Users/medialab
≈:≈

**Comment by dericed** [comment]
Seems like you don't have permission to add a folder in /Volumes.

**Comment by NMAAHC** [comment]
Yes, this is true. 

/Users/medialab
≈:≈ cd /Volumes/

/Volumes
≈:≈ mkdir uggh
mkdir: uggh: Permission denied

/Volumes
≈:≈ 

Can I chmod/chown /Volumes? Unsure what happened here, wasn't like this until this morning.

**Comment by dericed** [comment]
I renamed the issue for clarity.
