### ISSUE TITLE
Add option to not have tape eject when writing is finished

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#9]
We often need to add some final documentation to the tape that is not available until it is finished writing. It would be nice to have a flag in writelto (or maybe it is mountlto where it needs to be...) that would tell the script not to eject the tape until the user tells it to.

**Comment by dericed** [comment]
testing this with https://github.com/amiaopensource/ltopers/commit/60dcca85a12076ba44ffb468940fc5cd28b3d63d. It should work with:
`writelto -e N -t BLAKE1 /Volumes/video_cd_rips`

**Comment by NMAAHC** [comment]
Works like a charm. 
THANKS!

Back to archiving all those video cds now...
